name: Slash Command Dispatch
env:
    REPO_OWNER: "${{ vars.REPO_OWNER }}"
    REPO_NAME: "${{ vars.REPO_NAME }}"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [ closed ]

jobs:
  checkAutomatedPR:
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.issue.pull_request && contains(github.event.comment.body, '/package') }}
    uses: ./.github/workflows/checkAutomatedPR.yaml

  pullRequestStatus:
    if: ${{ !github.event.pull_request.head.repo.fork && github.event.issue.pull_request && contains(github.event.comment.body, '/package') }}
    uses: ./.github/workflows/pullRequestStatus.yaml

  addCommentOnOpenPullRequest:
    needs: pullRequestStatus
    if: ${{ success() && needs.pullRequestStatus.outputs.isPullRequestMerged == 'False' && github.event.action == 'created' && !github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/addComment.yaml
    with:
      message: 'Thank you for your comment. Team is reviewing your pull request content and will get back to you once done. Thank you for your patience.'

  slashCommandDispatch:
    runs-on: ubuntu-latest
    needs: [pullRequestStatus, checkAutomatedPR]
    if: ${{ success() && needs.pullRequestStatus.outputs.isPullRequestMerged == 'True' && needs.checkAutomatedPR.outputs.isAutomatedPR == 'False' && !github.event.pull_request.head.repo.fork}}
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@67dfeb76529b35541a7c536976cba367cd2d364b
        with:
          commands: package
          repository: ${{env.REPO_OWNER}}/${{env.REPO_NAME}}
          issue-type: pull-request
          reactions: false
